<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abdulhadi.Foundation.Identity.Application\Abdulhadi.Foundation.Identity.Application.csproj" />
    <ProjectReference Include="..\Abdulhadi.Foundation.Identity.Infrastructure\Abdulhadi.Foundation.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\BuildingBlocks.Identity\BuildingBlocks.Identity.csproj" />
    <ProjectReference Include="..\BuildingBlocks.Logging\BuildingBlocks.Logging.csproj" />
    <ProjectReference Include="..\BuildingBlocks.Monitoring\BuildingBlocks.Monitoring.csproj" />
    <ProjectReference Include="..\BuildingBlocks.Shared.API\BuildingBlocks.Shared.API.csproj" />
    <ProjectReference Include="..\BuildingBlocks.Shared.Contracts\BuildingBlocks.Shared.Contracts.csproj" />
  </ItemGroup>

</Project>
