<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Extensions\" />
    <Folder Include="Middleware\" />
    <Folder Include="RateLimiting\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\RESTful APIs\User Management\BuildingBlocks.Shared.Core\BuildingBlocks.Shared.Core.csproj" />
  </ItemGroup>

</Project>
