<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks.Shared.Contracts\BuildingBlocks.Shared.Contracts.csproj" />
    <ProjectReference Include="..\BuildingBlocks.Shared.Core\BuildingBlocks.Shared.Core.csproj" />
  </ItemGroup>

</Project>